/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasifutsal.form;

import aplikasifutsal.AplikasiFutsal;
import aplikasifutsal.controller.TeamController;
import aplikasifutsal.data.Team;
import com.toedter.calendar.JDateChooser;
import java.awt.Component;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Candi-PC
 */
public class FormTeam extends javax.swing.JInternalFrame implements NavigatorFormInt{

    TeamController tCont=new TeamController(AplikasiFutsal.emf);
    Team team=new Team();
    DefaultTableModel model;
    /**
     * Creates new form FormTeam
     */
    public FormTeam() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        this.setBorder(null);
        model=new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.addColumn("Kode Team");
        model.addColumn("Nama Team");
        model.addColumn("Kapten");
        model.addColumn("No HP");
        model.addColumn("Tanggal Daftar");
        model.addColumn("Status");
        model.addColumn("Keterangan");
        tableTeam.getTableHeader().setFont(new Font("Ubuntu Condensed", Font.ITALIC, 14));
        seleksiTable();
        renderTable();
    }
    
    private void setTanggal(){
        //membuat format waktu jam, hari bulan dan tahun dengan locale indonesia
        SimpleDateFormat sdf=new SimpleDateFormat("dd MMMM yyyy", Locale.forLanguageTag("in-ID"));
        Calendar cal=Calendar.getInstance();
        txtTanggal.setText(sdf.format(cal.getTime()));
    }
    
    private void showTableTeam(){
        tableTeam.setModel(tCont.showTable(model));
    }

    private void seleksiTable(){
        tableTeam.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int baris=tableTeam.getSelectedRow();       //dapatkan baris yang terseleksi
                if(baris != -1){                        //jika baris bukan sama dengan -1 atau tidak ada
                    txtKode.setText(tableTeam.getValueAt(baris, 0).toString());
                    txtNama.setText(tableTeam.getValueAt(baris, 1).toString());
                    txtKapten.setText(tableTeam.getValueAt(baris, 2).toString());
                    txtTelepon.setText(tableTeam.getValueAt(baris, 3).toString());
                    SimpleDateFormat sdf=new SimpleDateFormat("dd MMMM yyyy", Locale.forLanguageTag("in-ID"));
                    txtTanggal.setText(sdf.format(tableTeam.getValueAt(baris, 4)));
                    cmbStatus.setSelectedItem(tableTeam.getValueAt(baris, 5).toString());
                }
            }
        });
    }
    
    public void renderTable(){
        TableCellRenderer tbr = new DefaultTableCellRenderer(){
            SimpleDateFormat sdf=new SimpleDateFormat("dd MMMM yyyy", Locale.forLanguageTag("in-ID"));
            public Component getTableCellRendererComponent(JTable table,
                    Object value, boolean isSelected, boolean hasFocus,
                    int row, int column){
                if(value instanceof Date){
                    value = sdf.format(value);
                }
                return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            }
        };
        tableTeam.getColumnModel().getColumn(4).setCellRenderer(tbr);
    }
    
    private void cariTable(String cari){
        DefaultTableModel x=tCont.cari(model, cari);
        if(x.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "Data tidak ada!");
        }else{
            tableTeam.setModel(tCont.cari(model, cari));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtKode = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtKapten = new javax.swing.JTextField();
        txtTelepon = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        txtTanggal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTeam = new javax.swing.JTable();
        btCari = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setTitle("Form Team");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(22, 69, 24));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kode Team");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tanggal Daftar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 30));

        jLabel3.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Team");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 20));

        jLabel4.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kapten");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 20));

        jLabel5.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No HP");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));

        jLabel6.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Status");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, 20));

        txtKode.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jPanel1.add(txtKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 230, -1));

        txtNama.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 230, 30));

        txtKapten.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        txtKapten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKaptenActionPerformed(evt);
            }
        });
        jPanel1.add(txtKapten, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 230, 30));

        txtTelepon.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jPanel1.add(txtTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 230, 30));

        cmbStatus.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Member", "Non-Member" }));
        jPanel1.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 230, 30));

        txtTanggal.setFont(new java.awt.Font("Ubuntu Condensed", 0, 18)); // NOI18N
        jPanel1.add(txtTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 230, 30));

        jTabbedPane1.addTab("Master Team", jPanel1);

        jPanel2.setBackground(new java.awt.Color(22, 69, 24));

        tableTeam.setFont(new java.awt.Font("Ubuntu Condensed", 0, 14)); // NOI18N
        tableTeam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Team", "Nama Team", "Kapten", "No HP", "Tanggal Daftar", "Status"
            }
        ));
        jScrollPane1.setViewportView(tableTeam);

        btCari.setFont(new java.awt.Font("Ubuntu Condensed", 0, 14)); // NOI18N
        btCari.setText("Cari");
        btCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCariActionPerformed(evt);
            }
        });

        txtCari.setFont(new java.awt.Font("Ubuntu Condensed", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Ubuntu Condensed", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cari team");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCari)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lihat Data", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCariActionPerformed
        cariTable(txtCari.getText());
    }//GEN-LAST:event_btCariActionPerformed

    private void txtKaptenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKaptenActionPerformed
        
    }//GEN-LAST:event_txtKaptenActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        txtKode.setEnabled(false);
        txtTanggal.setEnabled(false);
        txtNama.setEnabled(false);
        txtKapten.setEnabled(false);
        txtTelepon.setEnabled(false);
        cmbStatus.setEnabled(false);
        txtCari.setEnabled(false);
        btCari.setEnabled(false);
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCari;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tableTeam;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtKapten;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtTelepon;
    // End of variables declaration//GEN-END:variables

    @Override
    public void aktif() {
        txtNama.setEnabled(true);
        txtKapten.setEnabled(true);
        txtTelepon.setEnabled(true);
        cmbStatus.setEnabled(true);
        txtCari.setEnabled(true);
        btCari.setEnabled(true);
        setTanggal();
        bersih();
    }

    @Override
    public void bersih() {
        txtNama.setText("");
        txtKapten.setText("");
        txtTelepon.setText("");
        cmbStatus.setSelectedIndex(0);
        txtCari.setText("");
        txtKode.setText(tCont.kodeTeamOto());
        showTableTeam();
        renderTable();
    }

    @Override
    public void simpan() {
        if("".equals(txtKode.getText())||"".equals(txtNama.getText())||"".equals(txtKapten.getText())||
                "".equals(txtTelepon.getText())){
            JOptionPane.showMessageDialog(null, "Data belum lengkap!");
        }else{
            Team team=tCont.findTeam(txtKode.getText());
            Team tm=new Team();
            if(team==null){
                tm.setKdTeam(txtKode.getText());
                tm.setTglDaftar(new Date());
                tm.setNmTeam(txtNama.getText());
                tm.setKapten(txtKapten.getText());
                tm.setNoHp(txtTelepon.getText());
                tm.setStatus(cmbStatus.getSelectedItem().toString());
                tm.setKeterangan("Belum Registrasi");
                try{
                    tCont.save(tm);
                }catch(Exception ex){}
                JOptionPane.showMessageDialog(null, "Data telah disimpan!");
            }else{
                tm.setKdTeam(txtKode.getText());
                try{
                SimpleDateFormat sdf=new SimpleDateFormat("dd MMMM yyyy", Locale.forLanguageTag("in-ID"));
                Date tgl=(Date) sdf.parse(txtTanggal.getText());
                tm.setTglDaftar(tgl);
            }catch(Exception ex){}
                tm.setNmTeam(txtNama.getText());
                tm.setKapten(txtKapten.getText());
                tm.setNoHp(txtTelepon.getText());
                tm.setStatus(cmbStatus.getSelectedItem().toString());
                tm.setKeterangan("Belum Registrasi");
                try{
                    tCont.update(tm);
                }catch(Exception ex){}
                JOptionPane.showMessageDialog(null, "Data telah diupdate!");
            }
            bersih();
        }
    }

    @Override
    public void hapus() {
        try{
            tCont.delete(txtKode.getText());
            JOptionPane.showMessageDialog(null, "Data telah di hapus!");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Data tidak bisa di hapus karena "+ex.getMessage());
        }
        bersih();
    }

    @Override
    public void cari() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void tampil() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
